Repository gingerzoealex/farset-membership-management, pull requests merged in 2018-09, with the labels that each got.

#14 Implement landing pack based upon designs
  services/client/public/index.html
  services/client/src/App.css
  services/client/src/App.js
  services/client/src/components/header/index.js
  services/client/src/components/header/styles/index.js
Labels: CSS, JavaScript, ReactJS

#11 Adding docker-compose and postgres db for users service
  docker-compose-dev.yml
  services/nginx/Dockerfile
  services/nginx/flask.conf
  services/users/entrypoint.sh
Labels: enhancement

#15 Adding docker support for client
  .gitignore
  README.md
  docker-compose-dev.yml
  services/client/.dockerignore
  services/client/Dockerfile-dev
  services/client/public/index.html
  services/nginx/flask.conf
  services/users/manage.py
Labels: Infrastructure, JavaScript, ReactJS

#24 members-service: Add database integration with PostgreSQL
  services/members-service/Pipfile
  services/members-service/Pipfile.lock
  services/members-service/application.py
Labels: python
